### ISSUE TITLE
ERROR!!!! ALERT ALERT!

### ISSUE THREAD

**Issue by alexkavon** [modubot/modubot.js#57]
Fix this please:
~~~
/srv/bot/node_modules/irc/lib/irc.js:735
    if ( args[args.length-1].match(/\s/) || args[args.length-1].match(/^:/) ||
                             ^
TypeError: undefined is not a function
    at Client.send (/srv/bot/node_modules/irc/lib/irc.js:735:30)
    at Client.notice (/srv/bot/node_modules/irc/lib/irc.js:844:10)
    at Bot.reply (/srv/bot/bin/Modubot/Bot.js:137:29)
    at Plugin.<anonymous> (/srv/bot/bin/plugins/kamaln7/google/google.js:21:26)
    at Request._callback (/srv/bot/node_modules/google/lib/google.js:57:7)
    at Request.self.callback (/srv/bot/node_modules/google/node_modules/request/main.js:122:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/srv/bot/node_modules/google/node_modules/request/main.js:661:16)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/srv/bot/node_modules/google/node_modules/request/main.js:623:14)
~~~

**Comment by kamaln7** [comment]
mocx please

https://github.com/martynsmith/node-irc

**Comment by reynir** [comment]
Assigned to me?! Wow rude.

**Comment by alexkavon** [comment]
kamaln7 pl0x

when was the last time the dependencies were updated?
